# Generated by Django 4.1.3 on 2022-12-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemascolumns',
            name='column_type',
            field=models.CharField(choices=[('Full name', 'Full name'), ('Job', 'Job'), ('Email', 'Email'), ('Domain name', 'Domain name'), ('Phone number', 'Phone number'), ('Company name', 'Company name'), ('Text', 'Text'), ('Integer', 'Integer'), ('Address', 'Address'), ('Date', 'Date')], max_length=12),
        ),
        migrations.AlterField(
            model_name='schemasgeneral',
            name='column_separator',
            field=models.CharField(choices=[(',', ' Comma (,)'), (';', 'Semicolon(;)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='schemasgeneral',
            name='modified',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='schemasgeneral',
            name='string_character',
            field=models.CharField(choices=[('"', 'Double-quote(")'), ('hz', 'hz')], max_length=2),
        ),
    ]
